const actionTypes = {
  INCREMENT: "INCREMENT",
  DECREMENT: "DECREMENT",

  REGISTER_REQUEST: "REGISTER_REQUEST",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_FAILURE: "REGISTER_FAILURE",
  CLEAR_REGISTRATION: "CLEAR_REGISTRATION",

  //verify otp
  SET_OTP_REQUEST: "SET_OTP_REQUEST",
  SET_OTP_SUCCESS: "SET_OTP_SUCCESS",
  SET_OTP_FAILURE: "SET_OTP_FAILURE",

  //Log in
  SET_LOGIN_REQUEST: "SET_LOGIN_REQUEST",
  SET_LOGIN_SUCCESS: "SET_LOGIN_SUCCESS",
  SET_LOGIN_FAILURE: "SET_LOGIN_FAILURE",

  //reset password
  SET_RESETPASSWORD_REQUEST:"SET_RESETPASSWORD_REQUEST",
  SET_RESETPASSWORD_SUCCESS:"SET_RESETPASSWORD_SUCCESS",
  SET_RESETPASSWORD_FAILURE:"SET_RESETPASSWORD_FAILURE",
};
export default actionTypes;
