const actionTypes = {
  INCREMENT: "INCREMENT",
  DECREMENT: "DECREMENT",

  REGISTER_REQUEST: "REGISTER_REQUEST",          
  REGISTER_SUCCESS: "REGISTER_SUCCESS",           
  REGISTER_FAILURE: "REGISTER_FAILURE",           
  CLEAR_REGISTRATION: "CLEAR_REGISTRATION",

  //verify otp
  SET_OTP_REQUEST : "SET_OTP_REQUEST",
  SET_OTP_SUCCESS:"SET_OTP_SUCCESS",
  SET_OTP_FAILURE:"SET_OTP_FAILURE"
};
export default actionTypes;
