const actionTypes = {
  INCREMENT: "INCREMENT",
  DECREMENT: "DECREMENT",

  REGISTER_REQUEST: "REGISTER_REQUEST",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_FAILURE: "REGISTER_FAILURE",
  CLEAR_REGISTRATION: "CLEAR_REGISTRATION",

  //verify otp
  SET_OTP_REQUEST: "SET_OTP_REQUEST",
  SET_OTP_SUCCESS: "SET_OTP_SUCCESS",
  SET_OTP_FAILURE: "SET_OTP_FAILURE",

  //Log in
  SET_LOGIN_REQUEST: "SET_LOGIN_REQUEST",
  SET_LOGIN_SUCCESS: "SET_LOGIN_SUCCESS",
  SET_LOGIN_FAILURE: "SET_LOGIN_FAILURE",

  //reset password
  SET_RESETPASSWORD_REQUEST:"SET_RESETPASSWORD_REQUEST",
  SET_RESETPASSWORD_SUCCESS:"SET_RESETPASSWORD_SUCCESS",
  SET_RESETPASSWORD_FAILURE:"SET_RESETPASSWORD_FAILURE",

  //log out 
   SET_LOGOUT : "SET_LOGOUT",

   //for slider
   GET_SLIDER_REQUEST:" GET_SLIDER_REQUEST",
   GET_SLIDER_SUCCESS:" GET_SLIDER_SUCCESS",
   GET_SLIDER_FAILURE:" GET_SLIDER_FAILURE",

   //for feature product
   GET_FEATURE_PRODUCT_REQUEST:"GET_FEATURE_PRODUCT_REQUEST",
   GET_FEATURE_PRODUCT_SUCCESS:" GET_FEATURE_PRODUCT_SUCCESS",
   GET_FEATURE_PRODUCT_FAILURE:"GET_FEATURE_PRODUCT_FAILURE",

   //most visited
  GET_MOST_VISITED_PRODUCT_REQUEST:"GET_MOST_VISITED_PRODUCT_REQUEST",
   GET_MOST_VISITED_PRODUCT_SUCCESS:"  GET_MOST_VISITED_PRODUCT_SUCCESS",
   GET_MOST_VISITED_PRODUCT_FAILURE:" GET_MOST_VISITED_PRODUCT_FAILURE",
   CLEAR_MOST_VISITED_PRODUCTS: 'CLEAR_MOST_VISITED_PRODUCTS',
  UPDATE_MOST_VISITED_FILTERS: 'UPDATE_MOST_VISITED_FILTERS',
};
export default actionTypes;
